Update elasticsearch cases build instructions
spgroup/mergedataset pull request #58
Opened 2021-02-24 01:04 UTC by rafaelmotaalves

Included the steps to install Gradle versions on the elasticsearch cases and fixed a git checkout instruction that had the wrong commit hash.

2021-02-24 19:51 UTC, leusonmario commented
@pauloborba Não está claro o que devo fazer. Devo tentar gerar os jars?

2021-02-24 20:29 UTC, pauloborba commented
> @pauloborba Não está claro o que devo fazer. Devo tentar gerar os jars?

só revisar

2021-02-26 18:47 UTC, rafaelmotaalves commented
@leusonmario adicionei a instrução em relação à versão do Java

2021-03-02 18:54 UTC, leusonmario requested changes

2021-03-02 18:54 UTC, leusonmario commented on elasticsearch/0404db65e3497452886173957729c8e82cfd4a03/README.md
> +   `gradle assemble testClasses`
Eu só consegui gerar a build depois de informar todo o path do gradle baixado.
Ao invés de rodar _gradle assemble testClasses_, eu usei _/opt/gradle/gradle-2.13/bin/gradle assemble testClasses_.

Talvez, poderia ser interessante adicionar isso no README, caso não funcione com o comando mais curto.

2021-03-02 18:54 UTC, leusonmario commented on elasticsearch/3764b3ff800c94293aba0bb0fa18c7df80a764f7/README.md
> +   `git checkout 3764b3ff800c94293aba0bb0fa18c7df80a764f7`
Não deveria ter as demais informações para os outros commits que compõem o cenário de merge (base, left, right)?

2021-03-02 18:54 UTC, leusonmario commented on elasticsearch/0404db65e3497452886173957729c8e82cfd4a03/README.md
> +   `gradle assemble testClasses`
Fiquei na dúvida se deveria ter as informações para gerar o jar com as dependências; ou essa é uma responsabilidade minha @pauloborba?

2021-03-02 18:54 UTC, leusonmario commented on elasticsearch/0404db65e3497452886173957729c8e82cfd4a03/README.md
> +   `gradle assemble testClasses`
Após executar o comando, indicar onde encontrar o jar gerado. Eu diria que seria nesse diretório `elasticsearch/core/build/libs`,certo?

2021-03-03 13:59 UTC, rafaelmotaalves commented on elasticsearch/3764b3ff800c94293aba0bb0fa18c7df80a764f7/README.md
> +   `git checkout 3764b3ff800c94293aba0bb0fa18c7df80a764f7`
@leusonmario  No caso do estudo de static-analysis, só geramos build para o commit de merge, por isso não inclui esses informações.

2021-03-03 14:00 UTC, rafaelmotaalves commented on elasticsearch/0404db65e3497452886173957729c8e82cfd4a03/README.md
> +   `gradle assemble testClasses`
Certo @leusonmario.Eu geralmente uso o comando find . -name *.jar para encontrar os jars, você acha melhor botar esse path ou o comando?

2021-03-03 21:36 UTC, leusonmario commented on elasticsearch/0404db65e3497452886173957729c8e82cfd4a03/README.md
> +   `gradle assemble testClasses`
@rafaelmotaalves acho melhor o comando considerando que pode haver dependências entre diferentes módulos etc.

2021-03-09 19:37 UTC, pauloborba commented on elasticsearch/0404db65e3497452886173957729c8e82cfd4a03/README.md
> +   `gradle assemble testClasses`
isso daí você pode ajustar no README @leusonmario , ou pedir para toni/vinicius ajustar.

2021-03-11 19:49 UTC, leusonmario commented on elasticsearch/0404db65e3497452886173957729c8e82cfd4a03/README.md
> +   `gradle assemble testClasses`
Ok @pauloborba. Acho que por mim, já pode ser integrado.

2021-03-12 01:39 UTC, merged