Adding changed-methods for issue #69
spgroup/mergedataset pull request #70
Opened 2021-10-07 21:08 UTC by galilasmb

2021-10-08 02:44 UTC, barbosamaatheus approved these changes

2021-10-08 05:03 UTC, leusonmario commented on vavr/204635d9156b498079c2f34b821dca7ca1711ef6/changed-methods/javaslang.collection.LinkedHashSet/of(T)/left-right-lines.csv
> +javaslang.collection.LinkedHashSet,source,92
Você verificou se de fato Left realiza alguma mudança neste método? Right realiza uma mudança no retorno, mas Left não muda nada em relação ao commit Base.

Mesmo assim, este cenário faz parte da amostra do estudo de vocês?

2021-10-08 15:50 UTC, galilasmb commented on vavr/204635d9156b498079c2f34b821dca7ca1711ef6/changed-methods/javaslang.collection.LinkedHashSet/of(T)/left-right-lines.csv
> +javaslang.collection.LinkedHashSet,source,92
Eu executei o script pra adicionar as linhas modificadas. Realmente left não fez nenhuma alteração, creio que estes cenários não sejam legais para usar como amostra.

2021-10-19 23:05 UTC, rafaelmotaalves approved these changes

2021-10-20 02:36 UTC, leusonmario requested changes
> Você verificou se de fato Left realiza alguma mudança neste método? Right realiza uma mudança no retorno, mas Left não muda nada em relação ao commit Base.
> Mesmo assim, este cenário faz parte da amostra do estudo de vocês?

O que foi decidido sobre os cenários onde não há mudanças entre os parent commits? Eles farão parte do dataset? @pauloborba 

Pergunto pois ainda há arquivos destes cenários.

2021-10-21 16:17 UTC, barbosamaatheus approved these changes

2021-10-21 20:22 UTC, pauloborba commented
> > Você verificou se de fato Left realiza alguma mudança neste método? Right realiza uma mudança no retorno, mas Left não muda nada em relação ao commit Base.
> > Mesmo assim, este cenário faz parte da amostra do estudo de vocês?
> 
> O que foi decidido sobre os cenários onde não há mudanças entre os parent commits? Eles farão parte do dataset? @pauloborba
> 
> Pergunto pois ainda há arquivos destes cenários.

@leusonmario você está falando dos casos em que há mudanças, mas apenas remoções de linhas?

se for isso, seria melhor deixar esses cenários no dataset aqui no GitHub, mas não usá-los nos estudos de análise estática. mas daria para usar no de análise dinâmica, não?

2021-10-21 20:47 UTC, pauloborba commented
> > > > Você verificou se de fato Left realiza alguma mudança neste método? Right realiza uma mudança no retorno, mas Left não muda nada em relação ao commit Base.
> > > > Mesmo assim, este cenário faz parte da amostra do estudo de vocês?
> > > 
> > > 
> > > O que foi decidido sobre os cenários onde não há mudanças entre os parent commits? Eles farão parte do dataset? @pauloborba
> > > Pergunto pois ainda há arquivos destes cenários.
> > 
> > 
> > @leusonmario você está falando dos casos em que há mudanças, mas apenas remoções de linhas?
> 
> Não, @pauloborba. Me refiro aos casos do projeto vavr. Nestes casos, apenas um parent realiza mudanças em relação à base, enquanto o outro não faz nada, não remove nem adiciona nada ([issue relacionada](https://github.com/spgroup/mergedataset/issues/69)).
> 
> > Eu executei o script pra adicionar as linhas modificadas. Realmente left não fez nenhuma alteração, creio que estes cenários não sejam legais para usar como amostra.
> 
> Quando perguntei sobre isso, há duas semanas, tive o feedback acima.
> 
> > se for isso, seria melhor deixar esses cenários no dataset aqui no GitHub, mas não usá-los nos estudos de análise estática. mas daria para usar no de análise dinâmica, não?
> 
> OK.

@rafaelmotaalves realmente não houve modificação alguma ou só houve remoção?

2021-11-29 21:45 UTC, barbosamaatheus commented
> Realmente remover os cenários do projeto VAVR?

eu acredito que não deveria ser excluído. É interessante ter a marcação dos arquivos modificados. Mesmo q seja só por left ou só por right. Num futuro isso pode ser útil em algum estudo.

2021-11-30 13:04 UTC, pauloborba commented
@rafaelmotaalves e @leusonmario alguma sugestão? temos no dataset uma forma de indicar que não houve modificações de left e right? sem isso, manter os cenários poluiria os estudos

2021-11-30 13:37 UTC, rafaelmotaalves commented
Acredito que seja o caso de remover mesmo. Porque nesse caso realmente não acontece mudanças no mesmo método, e ele só não sendo filtrado pelo miningframework por causa do bug que eu citei anteriormente. 

Que eu saiba não temos nenhum estudo que considera casos em que não houve mudanças no mesmo método certo?

2021-11-30 14:41 UTC, leusonmario commented
@pauloborba Concordo com a remoção destes cenários, desde quando realizei a primeira review desta PR.

2021-12-03 15:03 UTC, merged