Script fix
spgroup/mergedataset pull request #78
Opened 2023-05-13 01:34 UTC by ToniMaciel

1. Resolve issues present in the script responsible for generating SMAT input.
2. Make modifications to enable the inclusion of serialized jars version in the input.

2023-05-13 18:50 UTC, pauloborba requested changes

2023-05-13 18:50 UTC, pauloborba commented on semantic-conflicts/get_sample.py
> +        print("AQUI-2")
@ToniMaciel esquecesse de tirar isso?

2023-05-18 23:16 UTC, pauloborba commented
> Uma dúvida que tenho e sobre o tratamento adotado, caso um cenário de merge apresente mais de método alvo sendo modificado. Por exemplo, supondo que temos `metodoA e` `metodoB`, não faz diferença o jar usado para a análise feita com os jars `original` e `transformed` para os dois métodos. Entretanto, para os jars `serialized`, isso requer um tratamento especial por conta dos objetos serializados em cada método.
> 
> Eu não lembro de ter tratado isso, e no estudo da tese, eu devo ter configurado manualmente.

bem lembrado, @leusonmario !

2023-05-27 15:48 UTC, ToniMaciel commented
Só para atualizar essas últimas alterações:

- Fix do script para lidar com o problema dos jars serializados
- Renomeação dos jars serializados para o padrão atual produzido pelo OSean
- Movi os jars serializados do spring-boot - 6664ce pois eles eram do spring-boot - ea8107
- Coloquei novos jars de alguns projetos que estavam faltando, como HikariCP (método validate), elasticsearch-river-mongodb e spring-boot - 6664ce

2023-05-30 13:04 UTC, pauloborba approved these changes

2023-05-30 14:20 UTC, leusonmario approved these changes

2023-05-30 14:24 UTC, merged